name: CI

on: pull_request

jobs:
  unit-test:
    name: Testing / Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm test

  lint:
    name: Testing / Lint Staged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run lint-staged

  typescript-check:
    name: Testing / TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run typescript-check

  build:
    name: Deployment
    needs: [unit-test, lint, typescript-check]
    uses: ./.github/workflows/deploy.yml
